DROP TABLE IF EXISTS issues CASCADE;

CREATE TABLE issues (
    id SERIAL PRIMARY KEY NOT NULL,
    user_id, INTEGER REFERENCES users(id) ON DELETE CASCADE,
    issue_name VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    created_at DATE DEFAULT CURRENT_TIMESTAMP
)